import { createHash } from "node:crypto";
import type { ModelRequest, WorkflowGraphDocument } from "./schema.ts";
import { validateWorkflowGraphDocument } from "./validate.ts";
import { WorkflowStoreError, workflowStore } from "./store.ts";

export const ELEVATE_TO_DAG_MAX_PROMPT_CHARS = 32_768;

export interface ElevatePromptToDagInput {
  projectId: string;
  prompt: string;
  name?: string;
  workflowId?: string;
  defaultModel: ModelRequest;
  save?: boolean;
}

export interface ElevatePromptToDagResult {
  workflowId: string;
  revision: number | null;
  graph: WorkflowGraphDocument;
  saved: boolean;
}

export class ElevateToDagError extends Error {
  constructor(
    readonly code: "INVALID_PROMPT" | "INVALID_GRAPH" | "SAVE_FAILED",
    message: string,
  ) {
    super(message);
    this.name = "ElevateToDagError";
  }
}

export function elevateWorkflowId(prompt: string, explicit?: string): string {
  if (explicit && /^[a-z][a-z0-9_-]{0,63}$/.test(explicit)) return explicit;
  const digest = createHash("sha256").update(prompt).digest("hex").slice(0, 12);
  return `elevated_${digest}`;
}

/**
 * Deterministic elevator: one research-until-goal node whose goal is the
 * prompt. The saved document validates against NodeSpec v1. Chat (F9) and
 * the skill (F11) call this; they do not each build an elevator.
 */
export function buildElevatedWorkflowGraph(input: {
  prompt: string;
  name?: string;
  workflowId?: string;
  defaultModel: ModelRequest;
}): WorkflowGraphDocument {
  const prompt = input.prompt.trim();
  if (!prompt || prompt.length > ELEVATE_TO_DAG_MAX_PROMPT_CHARS) {
    throw new ElevateToDagError(
      "INVALID_PROMPT",
      "Elevate-to-DAG needs a non-empty prompt of at most 32768 characters.",
    );
  }
  const id = elevateWorkflowId(prompt, input.workflowId);
  return {
    schemaVersion: "1.0",
    id,
    name: input.name?.trim() || "Elevated workflow",
    description: "Generated by elevate-to-dag from a prompt.",
    entryNodeId: "research",
    defaultModel: input.defaultModel,
    limits: {
      maxIterations: 4,
      maxModelCalls: 32,
      maxParallelism: 4,
      maxSubagents: 4,
      timeoutMs: 30_000,
      maxTokens: 32_000,
      maxCostUsd: 8,
      maxRetries: 1,
    },
    evidence: {
      enabled: false,
      minimumIndependentSources: 0,
      requireArtifactReferences: false,
      onUnsupportedOutput: "route",
    },
    nodes: [
      {
        id: "research",
        name: "Research until goal",
        kind: "research-until-goal",
        terminal: true,
        workspace: { isolation: "read-only", writePaths: [] },
        goal: prompt,
        completionCriteria: [
          "The prompt's request is answered.",
          "Every material claim names its evidence.",
        ],
      },
    ],
    edges: [],
  };
}

export function elevatePromptToDag(input: ElevatePromptToDagInput): ElevatePromptToDagResult {
  const graph = buildElevatedWorkflowGraph(input);
  const validation = validateWorkflowGraphDocument(graph);
  if (!validation.ok) {
    throw new ElevateToDagError(
      "INVALID_GRAPH",
      `Elevated graph failed NodeSpec v1 validation: ${
        validation.issues.map((issue) => issue.message).join("; ")
      }`,
    );
  }
  if (!input.save) {
    return { workflowId: validation.document.id, revision: null, graph: validation.document, saved: false };
  }
  try {
    const saved = workflowStore.saveDefinition(
      input.projectId,
      validation.document.id,
      validation.document,
    );
    return {
      workflowId: saved.id,
      revision: saved.revision,
      graph: saved.graph,
      saved: true,
    };
  } catch (error) {
    if (error instanceof WorkflowStoreError) {
      throw new ElevateToDagError("SAVE_FAILED", error.message);
    }
    throw error;
  }
}
